### ISSUE TITLE
Spider on my roof

### ISSUE THREAD

**Issue by ToxicDanger** [SquareTable/social-media-platform#4]
A very large daddy long legs spider is on my roof

No it is no reproducing

Staying in one place in the corner, but will probably move around in a while

No screenshots, photos are available but cant be bothered taking a photo

Im not sure why i would need to specify my device but i could specify the species of spider
Common Daddy Long Legs Spider - Cellar Spider (Pholcidae)

Maybe vacuum it up

**Comment by Sebastian-Webster** [comment]
I have brought a vacuum cleaner to your house and vacuumed up the spider

The bug is now gone :)
Thank you for reporting it
